sudo: false
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
    - mongodb-org-shell
language: python
python:
- '3.4'
- '3.6'
before_install:
- mongo --version
- pip install -e .
install:
- pip install -U pytest>=2.8
script: py.test tests
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: ULpCyZJXkr3d0oZ6q2zxalfq/gVF9pBQ09yVzksXAgxtbPC/jC12Hn+CDJBql1a9LdnoBTfOfRUtnI1jTbaCeRuttWyf+fGFzp4V1zDxDX7GxM+p9A+uJt73HWTJW8EzYeeShb8DT05dWihu2dj+JbAFXcbaiXBlLm+jnPkk4Iz7mOgK+FAyw2cLVXfHFN0SoSGuwnTqePA6Yu2fGYiUNql0cqg4zIgzyJeuKrkb4VGyUwfSWpcVa62AeAGGLVBjW6hn/waHdsSoSx2B9Tkgw9wZN/curAOK6pmEmNoz/xZO7610M7cCSwxaHxATpmA9SbjXN73byo/fEPpt/PFBBYECfyLzsM/+dzyRAPf93dma3o6Sr2fvqca4Y1OiIPu0dQwxiUDZxBpxDU2CnIRaa2sxuLyi/bEbWJSwbHrt3u4RgmPNc+pf2yGVw1/pECWeG/b8/au6Gm413Pguep4z1F2aeDILt5ayEkWtalqlrvBBsI9EtDiqXbHgvZD/DvEsfCgGR0uAVvE1OnJAfY5AsQzrNXnOobtzqAKc5WjBkClbcWHunWA3e4fci/YzC+LN1Mp7JFeIrMsgI1DJrmzkz5t1I+7vhlBPDTEfTZcGmHvNkhQqpaK5K9vhc8vlxnp6G9sMo/JUA4cMQ8D+YjDecfpXEqZ/61LHi5zggHKab54=
  on:
    tags: true
    repo: touilleMan/mongopatcher
    python: 3.6
